<?php

add_action( 'acf/include_fields', function() {
    if ( ! function_exists( 'acf_add_local_field_group' ) ) {
        return;
    }

    acf_add_local_field_group( array(
        'key' => 'group_66fcd9ab827ea',
        'title' => 'community-events',
        'fields' => array(
            array(
                'key' => 'field_66fcd9aa396d1',
                'label' => 'Title',
                'name' => 'event_title',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'Meeting',
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'placeholder' => 'Meeting',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_66fcf8e5516ba',
                'label' => 'Beginn',
                'name' => 'event_start_date',
                'aria-label' => '',
                'type' => 'date_time_picker',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'display_format' => 'd.m.Y H:i',
                'return_format' => 'd.m.Y H:i',
                'first_day' => 1,
                'allow_in_bindings' => 0,
            ),
            array(
                'key' => 'field_66fcf960516bb',
                'label' => 'Ende',
                'name' => 'event_end_date',
                'aria-label' => '',
                'type' => 'date_time_picker',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'display_format' => 'd.m.Y H:i',
                'return_format' => 'd.m.Y H:i',
                'first_day' => 1,
                'allow_in_bindings' => 0,
            ),
            array(
                'key' => 'field_66fcf993516bc',
                'label' => 'Url zum Event',
                'name' => 'event_url',
                'aria-label' => '',
                'type' => 'url',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'https://comenius.de/rpi-zoom',
                'allow_in_bindings' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_66fcf9de516bd',
                'label' => 'ID der Gruppe',
                'name' => 'event_group_id',
                'aria-label' => '',
                'type' => 'acfe_hidden',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'allow_in_bindings' => 0,
            ),
            array(
                'key' => 'field_66fcfa17516be',
                'label' => 'Sichbarkeit',
                'name' => 'event_visibility',
                'aria-label' => '',
                'type' => 'select',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'group' => 'Nur für Mitglieder die Gruppe',
                    'logged_in' => 'Eingeladen sind alle angemeldeten Mitglieder der Community',
                    'guest' => 'Auch nicht angemeldete Besucher können teilnehmen',
                ),
                'default_value' => 'guest',
                'return_format' => 'value',
                'multiple' => 0,
                'allow_custom' => 0,
                'placeholder' => '',
                'search_placeholder' => '',
                'allow_null' => 0,
                'allow_in_bindings' => 0,
                'ui' => 0,
                'ajax' => 0,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'event_post',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'left',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
        'acfe_display_title' => '',
        'acfe_autosync' => '',
        'acfe_form' => 0,
        'acfe_meta' => '',
        'acfe_note' => '',
    ) );

    acf_add_local_field_group( array(
        'key' => 'group_669f7067938e7',
        'title' => 'Edit Group',
        'fields' => array(
            array(
                'key' => 'field_669f710f0edcc',
                'label' => 'Cover Bild',
                'name' => 'thumbnail',
                'aria-label' => '',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '100',
                    'class' => 'edit-thumbnail',
                    'id' => '',
                ),
                'uploader' => '',
                'return_format' => 'array',
                'library' => 'uploadedTo',
                'acfe_thumbnail' => 1,
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'preview_size' => 'medium',
            ),
            array(
                'key' => 'field_669f70690edc9',
                'label' => 'Name der Gruppe',
                'name' => 'group_title',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_669f70f00edcb',
                'label' => 'Zielsetzung',
                'name' => 'group_goal',
                'aria-label' => '',
                'type' => 'textarea',
                'instructions' => 'Beschreibe das gemeinsam verabredete Ziel dieser Gruppe kurz und prägnant .',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'acfe_textarea_code' => 0,
                'maxlength' => '',
                'allow_in_bindings' => 1,
                'rows' => 4,
                'placeholder' => '',
                'new_lines' => 'br',
            ),
            array(
                'key' => 'field_669f70a10edca',
                'label' => 'Worum geht es der Gruppe?',
                'name' => 'group_content',
                'aria-label' => '',
                'type' => 'wysiwyg',
                'instructions' => 'Beschreibe die Herausforderungen und thematischen Schwerkunkte, um die es in der Gruppe geht.',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'visual',
                'toolbar' => 'basic',
                'media_upload' => 1,
                'delay' => 0,
            ),
            array(
                'key' => 'field_66aa5decb7c4c',
                'label' => 'Beitrittsoption',
                'name' => '_join_option',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => 'Wenn du den Beitritt zu dieser Gruppe einschränkst und speicherst, erhält jedes Gruppenmitglied nach dem nächsten Aufruf des Formulars einen Knopf zum Kopieren des Einladelinks.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui_on_text' => 'Beitritt zur Gruppe nur mit Einladungslink',
                'ui_off_text' => 'Jedes Mitglied kann beitreten',
                'ui' => 1,
            ),
            array(
                'key' => 'field_66b87286c6172',
                'label' => 'EInlagungscode',
                'name' => '_invite_hash',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => 'Hinweis: Aus dem Einladungscode wird der Einladungslink generiert. Bisherige Einladungslinks werden nach einer Änderung ungültig.',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_66aa5decb7c4c',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'group_post',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'seamless',
        'label_placement' => 'left',
        'instruction_placement' => 'field',
        'hide_on_screen' => array(
            0 => 'permalink',
            1 => 'block_editor',
            2 => 'the_content',
            3 => 'excerpt',
            4 => 'discussion',
            5 => 'comments',
            6 => 'revisions',
            7 => 'slug',
            8 => 'author',
            9 => 'format',
            10 => 'page_attributes',
            11 => 'featured_image',
            12 => 'categories',
            13 => 'tags',
            14 => 'send-trackbacks',
        ),
        'active' => false,
        'description' => '',
        'show_in_rest' => 1,
        'acfe_display_title' => 'Edit Group',
        'acfe_autosync' => array(
            0 => 'php',
            1 => 'json',
        ),
        'acfe_form' => 0,
        'acfe_meta' => '',
        'acfe_note' => '',
    ) );

    acf_add_local_field_group( array(
        'key' => 'group_66f691a3bb4f1',
        'title' => 'Lernwerkzeuge',
        'fields' => array(
            array(
                'key' => 'field_66f691a19a897',
                'label' => 'Videokonferenz',
                'name' => 'group_tool_videoconference',
                'aria-label' => '',
                'type' => 'select',
                'instructions' => 'Wenn dieser Integration durch den Administrator deaktiviert ist, hat die auswahl keinen Effect',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'jitsi' => 'Meet Jitsi in den Lernraum integrieren',
                    'button' => 'Link zu einem Videokonferenzraum (Zoom/Talk/Teams..)',
                ),
                'default_value' => 'button',
                'return_format' => 'value',
                'multiple' => 0,
                'allow_null' => 0,
                'allow_in_bindings' => 0,
                'ui' => 0,
                'ajax' => 0,
                'placeholder' => '',
                'allow_custom' => 0,
                'search_placeholder' => '',
            ),
            array(
                'key' => 'field_66f693d9c37ba',
                'label' => 'Name der Konferenzsoftware (Zoom, Teams..)',
                'name' => 'group_tool_videoconference_label',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_66f691a19a897',
                            'operator' => '==',
                            'value' => 'button',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'allow_in_bindings' => 1,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_66f69362c37b9',
                'label' => 'Url zur Videokonferenz',
                'name' => 'group_tool_videoconference_url',
                'aria-label' => '',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_66f691a19a897',
                            'operator' => '==',
                            'value' => 'button',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'allow_in_bindings' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_66f6972122938',
                'label' => 'AI Integration',
                'name' => 'group_tool_ai_integration',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => 'KI Moderation und alle dazugehörige Funktionen verwenden',
                'default_value' => 1,
                'allow_in_bindings' => 0,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_66f69429d32ee',
                'label' => 'Whiteboard (Exclidraw)',
                'name' => 'group_tool_exclidraw',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => 'Link zu Excalidraw bereitstellen',
                'default_value' => 1,
                'allow_in_bindings' => 0,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_66fbe9e287457',
                'label' => 'OER-Maker',
                'name' => 'group_tool_oer_maker',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => 'LiaScript Live-Editor zum collaborativen Erstellen von Markdown basierten OER',
                'default_value' => 0,
                'allow_in_bindings' => 0,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_66f69526d32f0',
                'label' => 'Terminfinder (Nuudel)',
                'name' => 'group_tool_nuudel',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => 'Link zu Nuudel bereitstellen',
                'default_value' => 1,
                'allow_in_bindings' => 0,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_66fba7e1fe482',
                'label' => 'Url zum Matrixchannel',
                'name' => 'group_tool_matrixroom',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'allow_in_bindings' => 1,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_66f6959a89236',
                'label' => 'Eigene Tools',
                'name' => 'group_tool_custom_tools',
                'aria-label' => '',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'acfe_repeater_stylised_button' => 1,
                'layout' => 'table',
                'pagination' => 0,
                'min' => 0,
                'max' => 0,
                'collapsed' => '',
                'button_label' => 'Eintrag hinzufügen',
                'rows_per_page' => 20,
                'sub_fields' => array(
                    array(
                        'key' => 'field_66f695d089237',
                        'label' => 'Aktiv',
                        'name' => 'active',
                        'aria-label' => '',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'allow_in_bindings' => 0,
                        'ui' => 0,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                        'parent_repeater' => 'field_66f6959a89236',
                    ),
                    array(
                        'key' => 'field_66f6962589238',
                        'label' => 'Label',
                        'name' => 'label',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'allow_in_bindings' => 0,
                        'placeholder' => 'Cloud',
                        'prepend' => '',
                        'append' => '',
                        'parent_repeater' => 'field_66f6959a89236',
                    ),
                    array(
                        'key' => 'field_66f696b289239',
                        'label' => 'Url',
                        'name' => 'url',
                        'aria-label' => '',
                        'type' => 'url',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'allow_in_bindings' => 0,
                        'placeholder' => 'https://nextcloud.com/s/xyz',
                        'parent_repeater' => 'field_66f6959a89236',
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'group_post',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'left',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => false,
        'description' => '',
        'show_in_rest' => 0,
        'acfe_display_title' => '',
        'acfe_autosync' => '',
        'acfe_form' => 0,
        'acfe_meta' => '',
        'acfe_note' => '',
    ) );

    acf_add_local_field_group( array(
        'key' => 'group_66d6b5ec1c4ca',
        'title' => 'Optionspage',
        'fields' => array(
            array(
                'key' => 'field_66d6b5ecd8be1',
                'label' => 'Allgemein',
                'name' => '',
                'aria-label' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
                'selected' => 0,
            ),
            array(
                'key' => 'field_670143cfd9e3b',
                'label' => 'Hilfe-Widget',
                'name' => 'faq_button',
                'aria-label' => '',
                'type' => 'acfe_code_editor',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '<a class="button" href="/faq/" class="faq-button">Wie funktioniert das?</a>',
                'placeholder' => '',
                'mode' => 'text/html',
                'lines' => 1,
                'indent_unit' => 4,
                'maxlength' => '',
                'rows' => 4,
                'max_rows' => '',
                'return_format' => array(
                ),
                'allow_in_bindings' => 0,
            ),
            array(
                'key' => 'field_66f96b1fb0c69',
                'label' => 'Name Videokonferenzsoftware',
                'name' => 'videoconference_default_label',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'Jitsi Meet',
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_66f96145929de',
                'label' => 'Standard Url für Videokonferenzen',
                'name' => 'videoconference_default_url',
                'aria-label' => '',
                'type' => 'url',
                'instructions' => 'Standard Url zum Videokonferenzraum. Die Url wird auch verwendet für Plenumskonferenzen.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'https://meet.jit.si',
                'allow_in_bindings' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_66f96f18109e7',
                'label' => 'Minimal Gruppenmitglieder',
                'name' => 'group_builder_min_members',
                'aria-label' => '',
                'type' => 'number',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 2,
                'min' => '',
                'max' => '',
                'allow_in_bindings' => 0,
                'placeholder' => '',
                'step' => '',
                'prepend' => '',
                'append' => 'Notwendige Anzahl von Interessierten, um eine Gruppe gründen zu können',
            ),
            array(
                'key' => 'field_66f96eb0109e6',
                'label' => 'Maximal Gruppenmitglieder',
                'name' => 'group_builder_max_members',
                'aria-label' => '',
                'type' => 'number',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 5,
                'min' => '',
                'max' => '',
                'allow_in_bindings' => 0,
                'placeholder' => '',
                'step' => '',
                'prepend' => '',
                'append' => 'Max. zulässige Anzahl von Mitgliedern pro Gruppe',
            ),
            array(
                'key' => 'field_66f9704f290d9',
                'label' => 'Avatar Aktionen',
                'name' => 'group_builder_avatar_actions',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => 'Avatar Aktionsoptionen anzeigen',
                'default_value' => 1,
                'allow_in_bindings' => 0,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_66d6b67d1fbb1',
                'label' => 'Integrationen',
                'name' => '',
                'aria-label' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
                'selected' => 0,
            ),
            array(
                'key' => 'field_67055cb7ded85',
                'label' => 'Eigene Videokonferenzen für Gruppen',
                'name' => 'is_videoconference_header',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => 'Videokonferenz Kofpereich im Meetingraum integrieren',
                'default_value' => 0,
                'allow_in_bindings' => 0,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_66fa42af96338',
                'label' => 'Element/Matrix Integration',
                'name' => 'matrix_integration',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => 'Ist nicht implementiert. Eine Aktivierung hat keinen Effekt.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => 'Element Messenger App integrieren',
                'default_value' => 0,
                'allow_in_bindings' => 0,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_66fa435f98daa',
                'label' => 'Matrix Homeserver',
                'name' => 'matrix_homeserver',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'matrix.rpi-virtuell.de',
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'placeholder' => 'matrix.rpi-virtuell.de',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_66fa447464d0b',
                'label' => 'Link zum öffentlicher Diskussionschannel (Plenum)',
                'name' => 'matrix_plenum_url',
                'aria-label' => '',
                'type' => 'url',
                'instructions' => 'Wird auf der prominent beworden',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'allow_in_bindings' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_66ff09601c508',
                'label' => 'Martrix - Widget',
                'name' => 'martrix-widget-content',
                'aria-label' => '',
                'type' => 'acfe_code_editor',
                'instructions' => 'Platzhalter %url% für die Url zum Plenumschannel',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '<p>Wir nutzen den Element Messenger und schreiben uns dort im <a href="%url%" target="_blank">Raum KI-Strategie</a>. Alle Mitglieder sind herzlich eingeladen.</p>',
                'placeholder' => '',
                'mode' => 'text/html',
                'lines' => 1,
                'indent_unit' => 4,
                'maxlength' => '',
                'rows' => 4,
                'max_rows' => '',
                'return_format' => array(
                    0 => 'nl2br',
                ),
                'allow_in_bindings' => 0,
            ),
            array(
                'key' => 'field_66fa43df98dab',
                'label' => 'Element Gruppen',
                'name' => 'matrix_groups',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => 'Element Räume für jede Gruppe erzeugen',
                'default_value' => 1,
                'allow_in_bindings' => 0,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_66d6ba0c6af18',
                'label' => 'Url zum Etherpad',
                'name' => 'pad_base_url',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'https://etherpad.rpi-virtuell.de',
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'placeholder' => 'https://yopad.eu/',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_66d6b83b22086',
                'label' => 'Etherpad API KEY',
                'name' => 'pad_api_key',
                'aria-label' => '',
                'type' => 'password',
                'instructions' => 'Den API Key deines Etherpads findest du im Instatllationsverzeichnis des Eherpads in der Datei APIKEY.TXT',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'allow_in_bindings' => 0,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_66d715976adb7',
                'label' => 'Meet Jitsi Server',
                'name' => 'jitsi_server',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'jitsi.ff3l.net',
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_66d73a5b51999',
                'label' => 'Mit folgenden Jitsi Servern getestet:',
                'name' => '',
                'aria-label' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => 'freejitsi01.netcup.net
video.devloprog.org
jitsi.hamburg.ccc.de
meet.nerd.re
jitsi.freifunk-duesseldorf.de
jitsi.ff3l.net
meet.rpi-virtuell.de',
                'new_lines' => 'wpautop',
                'esc_html' => 0,
            ),
            array(
                'key' => 'field_66d9c31e21884',
                'label' => 'Excalidraw Url',
                'name' => 'whiteboard_url',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'https://excalidraw.com/',
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_66d6bb50b1312',
                'label' => 'HTML Vorlagen',
                'name' => '',
                'aria-label' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
                'selected' => 0,
            ),
            array(
                'key' => 'field_66ff0111538f5',
                'label' => 'Zum Gruppenstart',
                'name' => 'group_welcome_template',
                'aria-label' => '',
                'type' => 'acfe_code_editor',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '<h2>Get Started:</h2>
<p><strong>Willkommen!</strong><br>Gerade wurde die Gruppe gegründet. Nun kommen die nächsten Schritte...</p>\' .
<ul>\' .
<li>Schritt 1: Einigt Euch auf ein gemeinsames Ziel</li>\' .
<li>Schritt 2: Formuliert eure Aufgaben Herausforderungen (Vielleicht mit Hilfe der Pinnwand)</li>\' .
<li>Schritt 3: Verabredet den nächsten Termin</li>\' .
</ul>\' .
<p>Nutzt das Etherpad als für Eure Dokumentation im Meetingraum. Wenn ihr euch auf einen Termin geeinigt habt, tragt in im Formular (+ Termin ein).</p>
<p>Viel Erfolg beim ersten Treffen</p>
<hr>
<div>Ursprünglicher Inhalt an der Pinnwand: %pin%.\'</div>',
                'placeholder' => '',
                'mode' => 'text/html',
                'lines' => 1,
                'indent_unit' => 4,
                'maxlength' => '',
                'rows' => 4,
                'max_rows' => '',
                'return_format' => array(
                ),
                'allow_in_bindings' => 0,
            ),
            array(
                'key' => 'field_66ff026f23d43',
                'label' => 'Zum Gruppenstart (kopieren)',
                'name' => 'group_welcome_template_kopieren',
                'aria-label' => '',
                'type' => 'acfe_code_editor',
                'instructions' => 'Plazhalter für ursprünglichen Pinwandbeitrag %pin%',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '<div class="group-goal">
<h2>Get Started:</h2>
<p><strong>Willkommen!</strong><br>Gerade wurde die Gruppe gegründet. Nun kommen die nächsten Schritte...</p>\' .
<ul>\' .
<li>Schritt 1: Einigt Euch auf ein gemeinsames Ziel</li>\' .
<li>Schritt 2: Formuliert eure Aufgaben Herausforderungen (Vielleicht mit Hilfe der Pinnwand)</li>\' .
<li>Schritt 3: Verabredet den nächsten Termin</li>\' .
</ul>\' .
<p>Nutzt das Etherpad als für Eure Dokumentation im Meetingraum. Wenn ihr euch auf einen Termin geeinigt habt, tragt in im Formular (+ Termin ein).</p>
<p>Viel Erfolg beim ersten Treffen</p>
<hr>
<div>Ursprünglicher Inhalt an der Pinnwand: %pin%.\'</div>
</div>',
                'placeholder' => '',
                'mode' => 'text/html',
                'lines' => 1,
                'indent_unit' => 4,
                'maxlength' => '',
                'rows' => 4,
                'max_rows' => '',
                'return_format' => array(
                ),
                'allow_in_bindings' => 0,
            ),
            array(
                'key' => 'field_66da22acc4021',
                'label' => 'Konstituierendes Treffen',
                'name' => 'etherpad_initial_template',
                'aria-label' => '',
                'type' => 'acfe_code_editor',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '<h1>Konstituierendes Meeting - {TODAY}</h1><br>
<ul class="bullet">
		<li>Gruppe: {GROUPNAME}</li>
		<li>Datum: {STARTTIME}</li>
		<li>Anwesende: {USER}, </li>
</ul><br>
<h2>Ziel unserer Gruppe:</h2><br>
<br><br>
<h2>Herausforderungen und Aufgaben:</h2><br>
<ol start="1" class="number">
		<li>...</li>
</ol><br>

<br>
-------------------------------------------
<br>
Wenn ihr Ziel und Herausforderungen formuliert habt, klickt auf <strong>"Wir sind fertig!"</strong>. Die KI überträgt Eure Eingaben auf die Gruppenseite.
<br>
Was dann noch fehlt ist vielleicht	ein ansprechendes Bild:
<br>
<strong>Hier ein paar Werkzeuge, wie Ihr ein solches mit KI kostenlos generieren könnt:</strong>
<ul class="bullet">
		<li>https://huggingface.co/spaces/black-forest-labs/FLUX.1-schnell</li>
		<li>https://huggingface.co/spaces/black-forest-labs/FLUX.1-dev</li>
		<li>https://huggingface.co/spaces/mukaist/Midjourney</li>
</ul><br>',
                'placeholder' => '',
                'mode' => 'text/html',
                'lines' => 1,
                'indent_unit' => 4,
                'maxlength' => '',
                'rows' => 4,
                'max_rows' => '',
                'return_format' => array(
                ),
                'allow_in_bindings' => 1,
            ),
            array(
                'key' => 'field_66d6bb898b84e',
                'label' => 'Meeting Agenda',
                'name' => 'etherpad_agenda_template',
                'aria-label' => '',
                'type' => 'acfe_code_editor',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '<h1>Meeting -Agenda - {TODAY}</h1><br>
<ul class="bullet">
		<li>Gruppe: {GROUPNAME}</li>
		<li>Datum: {STARTTIME}</li>
		<li>Anwesende: {USER}, </li>
</ul><br>
<h2>Ziel dieses Treffens:</h2><br>
<br><br>
<h2>Tagesordnungspunkte:</h2><br>
<ol start="1" class="number">
		<li>...</li>
</ol><br>
<h2>Verabredungen und Absprachen:</h2>
<br>Wer macht was bis wann?<br>
<br>N&#228;chster Termin:&nbsp;<br>
<br>
<h2>Anmerkungen und Notizen:</h2>
<br>
<br>
<h2>Reflexion:</h2>
<br>Was hat gut geklappt?<br>
<br>Was wollen wir verbessern:<br>
<br>
<h2>Ergebnisse:</h2><br>
<br>
<br>Was davon wollen wir im Plenum berichten:<br>',
                'placeholder' => '',
                'mode' => 'text/html',
                'lines' => 1,
                'indent_unit' => 4,
                'maxlength' => '',
                'rows' => 30,
                'max_rows' => '',
                'return_format' => array(
                    0 => 'htmlentities',
                ),
                'allow_in_bindings' => 1,
            ),
            array(
                'key' => 'field_66d6c1fd04cc6',
                'label' => 'KI-Moderation',
                'name' => '',
                'aria-label' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
                'selected' => 0,
            ),
            array(
                'key' => 'field_67076c8f56a7e',
                'label' => 'Name des KI-Moderators',
                'name' => 'bot_name',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '33',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'KI-Bot',
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_670a82383b5ce',
                'label' => 'Wartezeiten zwischen Antworten',
                'name' => 'options_ai_wait_time',
                'aria-label' => '',
                'type' => 'number',
                'instructions' => 'Wartezeit, bevor eine KI Aktion erneut ausgeführt werden. Ausnahme Chat.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 5,
                'min' => '',
                'max' => '',
                'allow_in_bindings' => 0,
                'placeholder' => '',
                'step' => 1,
                'prepend' => '',
                'append' => 'Minuten',
            ),
            array(
                'key' => 'field_66d6c0cafd731',
                'label' => 'OpenAI LLM Model',
                'name' => 'openai_model',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'gpt-4o-mini',
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_66d6b6a32aee9',
                'label' => 'OpenAI API Key',
                'name' => 'openai_api_key',
                'aria-label' => '',
                'type' => 'password',
                'instructions' => 'Hier findest du deine AP KEYS https://platform.openai.com/api-keys',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'allow_in_bindings' => 1,
                'placeholder' => 'sk-...',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_6707ef779eab9',
                'label' => 'Systemprompt',
                'name' => 'system_prompt',
                'aria-label' => '',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '66',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'Du moderierst Schulentwicklung in evangelischen Schulen, förderst pädagogische Konzepte						digitale Tools und KI-Einsatz. Du vermittelst praxisnah Methoden, stärkst evangelische Werte, Vielfalt und interreligiösen Dialog. Du kennst deutsche Bildungsstandards und schulrechtliche Rahmenbedingungen.',
                'acfe_textarea_code' => 0,
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'rows' => '',
                'placeholder' => '',
                'new_lines' => '',
            ),
            array(
                'key' => 'field_66d6c06f3e3b9',
                'label' => 'Prompts',
                'name' => 'prompts',
                'aria-label' => '',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'acfe_repeater_stylised_button' => 1,
                'layout' => 'row',
                'pagination' => 0,
                'min' => 0,
                'max' => 0,
                'collapsed' => '',
                'button_label' => 'Eintrag hinzufügen',
                'rows_per_page' => 20,
                'sub_fields' => array(
                    array(
                        'key' => 'field_66d6c3d106422',
                        'label' => 'Button Name',
                        'name' => 'label',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => 30,
                        'allow_in_bindings' => 0,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'parent_repeater' => 'field_66d6c06f3e3b9',
                    ),
                    array(
                        'key' => 'field_66d6c44e753c6',
                        'label' => 'Icon',
                        'name' => 'icon',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 'dashicons-format-status',
                        'maxlength' => '',
                        'allow_in_bindings' => 0,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '<a href="https://developer.wordpress.org/resource/dashicons" target="_blank">WP DashIcons</a>',
                        'parent_repeater' => 'field_66d6c06f3e3b9',
                    ),
                    array(
                        'key' => 'field_66d6c18e49d55',
                        'label' => 'Key',
                        'name' => 'key',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => 'Eindeudige Bezeichnung, kleingeschrieben ohne Leerzeichen',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'allow_in_bindings' => 0,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'parent_repeater' => 'field_66d6c06f3e3b9',
                    ),
                    array(
                        'key' => 'field_6703d540e0459',
                        'label' => 'Erklärung',
                        'name' => 'description',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'allow_in_bindings' => 0,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'parent_repeater' => 'field_66d6c06f3e3b9',
                    ),
                    array(
                        'key' => 'field_66da1209984d7',
                        'label' => 'Benachrichtigung',
                        'name' => 'message',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'allow_in_bindings' => 0,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'parent_repeater' => 'field_66d6c06f3e3b9',
                    ),
                    array(
                        'key' => 'field_66d6c1b849d56',
                        'label' => 'Prompt',
                        'name' => 'prompt',
                        'aria-label' => '',
                        'type' => 'acfe_code_editor',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => 'Anweisung in Markdown',
                        'mode' => 'text/html',
                        'lines' => 1,
                        'indent_unit' => 4,
                        'maxlength' => '',
                        'rows' => 4,
                        'max_rows' => '',
                        'return_format' => array(
                        ),
                        'allow_in_bindings' => 1,
                        'parent_repeater' => 'field_66d6c06f3e3b9',
                    ),
                    array(
                        'key' => 'field_66d6c5b57ac32',
                        'label' => 'Kontext',
                        'name' => 'context',
                        'aria-label' => '',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'challenge' => 'Herausforderungen und Aufgaben',
                            'goal' => 'Gesamtziel der Gruppe',
                            'pad' => 'Inhalt des Etherpads',
                            'chat' => 'Inhalt der Chatbeiträge',
                            'history' => 'Protokolle der Gruppenarbeit',
                            'progress' => 'KI Fortschrittsbeobachtungen',
                        ),
                        'default_value' => array(
                            0 => 'pad',
                        ),
                        'return_format' => 'value',
                        'multiple' => 1,
                        'allow_custom' => 0,
                        'placeholder' => '',
                        'allow_null' => 0,
                        'allow_in_bindings' => 0,
                        'ui' => 1,
                        'ajax' => 0,
                        'search_placeholder' => '',
                        'parent_repeater' => 'field_66d6c06f3e3b9',
                    ),
                    array(
                        'key' => 'field_66d842369f1ab',
                        'label' => 'Output',
                        'name' => 'output',
                        'aria-label' => '',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'pad' => 'am Ende des Etherpads anfügen',
                            'chat' => 'als Chatbeitrag formulieren',
                            'history' => 'in die History der Gruppe schreiben',
                            'comment' => 'als Kommentar in die Gruppe schreiben',
                            'progress' => 'Fortschritt dokumentieren',
                            'message' => 'Ausgabe als Info im Popupfenster',
                        ),
                        'default_value' => false,
                        'return_format' => 'value',
                        'multiple' => 0,
                        'allow_null' => 0,
                        'allow_in_bindings' => 0,
                        'ui' => 0,
                        'ajax' => 0,
                        'placeholder' => '',
                        'allow_custom' => 0,
                        'search_placeholder' => '',
                        'parent_repeater' => 'field_66d6c06f3e3b9',
                    ),
                    array(
                        'key' => 'field_66d6c25c0d1bd',
                        'label' => 'Sichtbar',
                        'name' => 'active',
                        'aria-label' => '',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => 'Soll der Button in der Toolbar angezeigt werden?',
                        'default_value' => 0,
                        'allow_in_bindings' => 0,
                        'ui' => 0,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                        'parent_repeater' => 'field_66d6c06f3e3b9',
                    ),
                    array(
                        'key' => 'field_66d8872218357',
                        'label' => 'Einmalig',
                        'name' => 'singleplay',
                        'aria-label' => '',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => 'Soll diese Aktion nur einmalig durchgeführt werden?',
                        'default_value' => 0,
                        'allow_in_bindings' => 0,
                        'ui' => 0,
                        'ui_on_text' => '',
                        'ui_off_text' => '',
                        'parent_repeater' => 'field_66d6c06f3e3b9',
                    ),
                ),
            ),
            array(
                'key' => 'field_670771adf450e',
                'label' => 'Debug AI Promps',
                'name' => 'debug_ai_prompts',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => 'Entwicklerfunktion zum Prüfen der Prompts',
                'default_value' => 0,
                'allow_in_bindings' => 0,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_6707714cf450d',
                'label' => 'Debug AI Answers',
                'name' => 'debug_ai_answers',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => 'Entwicklerfunktion zum Prüfen der KI-generierten antworten',
                'default_value' => 0,
                'allow_in_bindings' => 0,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_6703bbec549e7',
                'label' => 'KI-Assistenz',
                'name' => '',
                'aria-label' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
                'selected' => 0,
            ),
            array(
                'key' => 'field_6703bc44549e8',
                'label' => 'Prompts',
                'name' => 'assist',
                'aria-label' => '',
                'type' => 'repeater',
                'instructions' => 'Die Prompts beziehen sich auf PhP-Funktionen im Quellcode. Einträge in der Spalte "Function" sollten nicht geändert werden! Prompts können angepasst werden, um bessere Ergebniss zu erziehlen.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'acfe_repeater_stylised_button' => 0,
                'layout' => 'table',
                'pagination' => 0,
                'min' => 0,
                'max' => 0,
                'collapsed' => '',
                'button_label' => 'Eintrag hinzufügen',
                'rows_per_page' => 20,
                'sub_fields' => array(
                    array(
                        'key' => 'field_6703bd0310794',
                        'label' => 'Function',
                        'name' => 'key',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'allow_in_bindings' => 0,
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'parent_repeater' => 'field_6703bc44549e8',
                    ),
                    array(
                        'key' => 'field_6703bce010793',
                        'label' => 'Prompt',
                        'name' => 'prompt',
                        'aria-label' => '',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'acfe_textarea_code' => 0,
                        'maxlength' => '',
                        'allow_in_bindings' => 1,
                        'rows' => '',
                        'placeholder' => '',
                        'new_lines' => '',
                        'parent_repeater' => 'field_6703bc44549e8',
                    ),
                ),
            ),
            array(
                'key' => 'field_66fed013614ad',
                'label' => 'Assets',
                'name' => '',
                'aria-label' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
                'selected' => 0,
            ),
            array(
                'key' => 'field_66fed02a4750b',
                'label' => 'Hintergrundbilder',
                'name' => 'bg_images',
                'aria-label' => '',
                'type' => 'gallery',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'library' => 'all',
                'min' => '',
                'max' => '',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'insert' => 'append',
                'preview_size' => 'medium',
            ),
            array(
                'key' => 'field_6708f28997d7b',
                'label' => 'E-Mail Benachrichtigungen',
                'name' => '',
                'aria-label' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
                'selected' => 0,
            ),
            array(
                'key' => 'field_6708f2ac97d7c',
                'label' => 'Termin Erinnerung Gruppe',
                'name' => 'remember_event_group_email',
                'aria-label' => '',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'Der Termin \'{event_title}\' findet morgen statt. Wir freuen uns auf Ihre Teilnahme!
Link: {event_url}',
                'acfe_textarea_code' => 0,
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'rows' => '',
                'placeholder' => '',
                'new_lines' => '',
            ),
            array(
                'key' => 'field_6708f59897d7d',
                'label' => 'Termin Erinnerung Alle Member',
                'name' => 'remember_event_email',
                'aria-label' => '',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'Der Termin \'{event_title}\' findet morgen statt. Wir freuen uns auf Ihre Teilnahme!
Link: {event_url}',
                'acfe_textarea_code' => 0,
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'rows' => '',
                'placeholder' => '',
                'new_lines' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'community-settings',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'left',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
        'acfe_display_title' => '',
        'acfe_autosync' => '',
        'acfe_form' => 0,
        'acfe_meta' => '',
        'acfe_note' => '',
    ) );

    acf_add_local_field_group( array(
        'key' => 'group_62cef43f88be3',
        'title' => 'Pinwand Post erstellen',
        'fields' => array(
            array(
                'key' => 'field_62cef4d976ad2',
                'label' => 'Frage/Idee ...',
                'name' => 'post_title',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_62cef52b76ad3',
                'label' => 'Worum geht es?',
                'name' => 'post_content',
                'aria-label' => '',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 1,
                'delay' => 0,
            ),
            array(
                'key' => 'field_62cef54376ad4',
                'label' => 'Öffentlich',
                'name' => 'public',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => 'hidden',
                    'id' => '',
                ),
                'message' => 'Für unangemeldete Besucher:innen sichtbar machen?',
                'default_value' => 1,
                'allow_in_bindings' => 1,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
            array(
                'key' => 'field_62cef58476ad5',
                'label' => 'Post Status',
                'name' => 'post_status',
                'aria-label' => '',
                'type' => 'acfe_hidden',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => 'hidden',
                    'id' => '',
                ),
                'default_value' => 'publish',
            ),
            array(
                'key' => 'field_62cef5eb76ad6',
                'label' => 'Kategorien',
                'name' => 'categories',
                'aria-label' => '',
                'type' => 'taxonomy',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'taxonomy' => 'pinwall_category',
                'add_term' => 1,
                'save_terms' => 1,
                'load_terms' => 1,
                'return_format' => 'id',
                'field_type' => 'checkbox',
                'acfe_bidirectional' => array(
                    'acfe_bidirectional_enabled' => '0',
                ),
                'allow_in_bindings' => 1,
                'bidirectional' => 0,
                'multiple' => 0,
                'allow_null' => 0,
                'bidirectional_target' => array(
                ),
            ),
            array(
                'key' => 'field_62cef61f76ad7',
                'label' => 'Schlagworte',
                'name' => 'tags',
                'aria-label' => '',
                'type' => 'taxonomy',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => 'hidden',
                    'id' => '',
                ),
                'taxonomy' => 'pinnwall_tag',
                'add_term' => 1,
                'save_terms' => 1,
                'load_terms' => 1,
                'return_format' => 'id',
                'field_type' => 'checkbox',
                'acfe_bidirectional' => array(
                    'acfe_bidirectional_enabled' => '0',
                ),
                'bidirectional' => 0,
                'multiple' => 0,
                'allow_null' => 0,
                'bidirectional_target' => array(
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'all',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'left',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => false,
        'description' => '',
        'show_in_rest' => 0,
        'acfe_display_title' => '',
        'acfe_autosync' => array(
            0 => 'php',
            1 => 'json',
        ),
        'acfe_form' => 0,
        'acfe_meta' => '',
        'acfe_note' => '',
    ) );
} );

